{ config, pkgs, inputs, ...  }:

{
  imports = [
    ./hardware-configuration.nix # Auto-generated by `nixos-generate-config`
  ];

  # Bootloader
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  
  # Networking
  networking.hostName = "nixos";
  networking.networkmanager.enable = true;

  # Timezone and locale
  time.timeZone = "Europe/Berlin";
  i18n.defaultLocale = "en_US.UTF-8";

  # Users
  users.users.nixon = {
    isNormalUser = true;
    description = "user nixon (default)";
    extraGroups = [ "networkmanager" "wheel" ];
    packages = with pkgs; [
      helix
      neovim
      vim
      git  
    ];
  };

 # Enable flakes
 nix.settings.experimental-features = [ "nix-command" "flakes" ];

 # Basic system-level packages
 environment.systemPackages = with pkgs; [
   vim
   helix
   git
   wget
   curl
 ];

 system.stateVersion = "25.11";
 
}
